apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxmox-provider-manager-secrets-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: proxmox-provider-manager-secrets
subjects:
- kind: ServiceAccount
  name: default
  namespace: proxmox-provider-system
